# Projet Voltit

Voici l'export de Juin. Aidez-nous à comprendre l'activité du réseau et à identifier les points qui méritent notre attention.

données (qualité - data ingénierie) → question(s) → observation des données → hypothèses (données) → transformations (pandas) → contrôle le résultat → interprétation (datavisualisation)

In [27]:
import pandas as pd

pd.__version__

'3.0.6'

# Observation

## Quelques questions

- Quel semble être le rôle de chacun des 4 fichiers ?
- Quelles colonnes vous semblent importantes
- Quelles questions métiers pensez-vous déjà pouvoir poser avec ces données
  - Quelles stations ont le plus d'activité ?
  - Combien d'énergie est délivrée ?
  - Quelles sont les tranches horaires d'activités ?
  - Combien coûte la maintenance ?
  - Maintenance et l'activité sont liées ?
- Voyez-vous déjà des éléments qui nécessiteront une interprétation plutôt qu'un simple calcul ?
- C'est quoi l'activité de l'entreprise ?

In [28]:
stations = pd.read_csv("./data/stations.csv")
sessions = pd.read_csv("./data/sessions.csv")
maintenance = pd.read_csv("./data/maintenance.csv")
telemetry = pd.read_csv("./data/telemetry.csv")

In [29]:
stations.shape

(20, 7)

In [30]:
sessions.shape

(2318, 7)

In [31]:
stations.head(10)

,station_id,station_name,district,site_type,opened_on,connector_count,connector_max_power_kw
0,ST001,Voltit 01,Centre,residential,2026-06-01,2,22.0
1,ST002,Voltit 02,Sud,office,2026-06-01,6,11.0
2,ST003,Voltit 03,Centre,retail,2026-06-01,4,11.0
3,ST004,Voltit 04,Nord,residential,2026-06-01,3,22.0
4,ST005,Voltit 05,Est,residential,2026-06-01,6,11.0
5,ST006,Voltit 06,Ouest,retail,2026-06-01,2,22.0
6,ST007,Voltit 07,Nord,retail,2026-06-01,4,11.0
7,ST008,Voltit 08,Sud,office,2026-06-01,5,11.0
8,ST009,Voltit 09,Est,residential,2026-06-01,2,11.0
9,ST010,Voltit 10,Nord,retail,2026-06-01,6,22.0

In [32]:
stations.tail(10)

,station_id,station_name,district,site_type,opened_on,connector_count,connector_max_power_kw
10,ST011,Voltit 11,Est,retail,2026-06-01,5,7.4
11,ST012,Voltit 12,Sud,office,2026-06-01,5,22.0
12,ST013,Voltit 13,Ouest,office,2026-06-01,6,11.0
13,ST014,Voltit 14,Centre,office,2026-06-01,5,22.0
14,ST015,Voltit 15,Ouest,office,2026-06-01,4,11.0
15,ST016,Voltit 16,Ouest,residential,2026-06-01,6,11.0
16,ST017,Voltit 17,Sud,retail,2026-06-01,6,22.0
17,ST018,Voltit 18,Nord,office,2026-06-01,2,22.0
18,ST019,Voltit 19,Centre,residential,2026-06-01,3,7.4
19,ST020,Voltit 20,Est,residential,2026-06-16,2,22.0

In [33]:
sessions.tail(10)

,session_id,station_id,connector_no,started_at,ended_at,energy_kwh,status
2308,SE002309,ST017,1,2026-06-30 20:57:00,2026-06-30 22:45:00,16.382,completed
2309,SE002310,ST005,2,2026-06-30 21:16:00,NaN,2.919,ongoing
2310,SE002311,ST015,4,2026-06-30 22:12:00,NaN,1.617,ongoing
2311,SE002312,ST016,5,2026-06-30 22:20:00,NaN,4.203,ongoing
2312,SE002313,ST020,2,2026-06-30 22:20:00,NaN,23.786,ongoing
2313,SE002314,ST015,1,2026-06-30 22:48:00,NaN,6.239,ongoing
2314,SE002315,ST003,1,2026-06-30 23:00:00,NaN,5.442,ongoing
2315,SE002316,ST017,6,2026-06-30 23:20:00,NaN,7.124,ongoing
2316,SE002317,ST011,3,2026-06-30 23:32:00,NaN,0.763,ongoing
2317,SE002318,ST010,3,2026-06-30 23:41:00,NaN,3.002,ongoing

In [34]:
energy = sessions["energy_kwh"]
energy.median()

np.float64(11.6765)

In [35]:
subset = sessions[["station_id", "energy_kwh"]]
subset

     station_id  energy_kwh
0         ST003       2.026
1         ST002       5.706
2         ST008      21.035
3         ST018      57.397
4         ST011       9.153
...         ...         ...
2313      ST015       6.239
2314      ST003       5.442
2315      ST017       7.124
2316      ST011       0.763
2317      ST010       3.002

[2318 rows x 2 columns]

In [36]:
sessions.groupby("station_id")["energy_kwh"].mean().round(2)

station_id
ST002    20.63
ST003     6.25
ST004    47.63
ST005    23.32
ST006    11.06
ST007     6.03
ST008    18.18
ST009    25.52
ST010    12.69
ST011     3.64
ST012    40.39
ST013    18.69
ST014    38.35
ST015    18.40
ST016    23.12
ST017    12.28
ST018    34.90
ST019    15.24
ST020    41.45
Name: energy_kwh, dtype: float64

In [37]:
sessions.loc[
    sessions["energy_kwh"] == 0,
    ["station_id", "energy_kwh"]
]

     station_id  energy_kwh
11        ST008         0.0
34        ST011         0.0
72        ST007         0.0
83        ST002         0.0
95        ST002         0.0
...         ...         ...
2208      ST003         0.0
2210      ST004         0.0
2212      ST020         0.0
2230      ST011         0.0
2259      ST018         0.0

[97 rows x 2 columns]

In [38]:
sessions.describe().round(2)

       connector_no  energy_kwh
count       2318.00     2318.00
mean           2.92       18.02
std            1.57       18.62
min            1.00        0.00
25%            2.00        5.33
50%            3.00       11.68
75%            4.00       24.36
max            6.00      141.82

In [41]:
sessions.dtypes

session_id          str
station_id          str
connector_no      int64
started_at          str
ended_at            str
energy_kwh      float64
status              str
dtype: object

In [43]:
sessions.info()

<class 'pandas.DataFrame'>
RangeIndex: 2318 entries, 0 to 2317
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   session_id    2318 non-null   str
 1   station_id    2318 non-null   str
 2   connector_no  2318 non-null   int64
 3   started_at    2318 non-null   str
 4   ended_at      2304 non-null   str
 5   energy_kwh    2318 non-null   float64
 6   status        2318 non-null   str
dtypes: float64(1), int64(1), str(5)
memory usage: 126.9 KB

In [46]:
sessions.dtypes

session_id                 str
station_id                 str
connector_no             int64
started_at      datetime64[us]
ended_at        datetime64[us]
energy_kwh             float64
status                     str
dtype: object

In [50]:
sessions.isna().sum()

session_id       0
station_id       0
connector_no     0
started_at       0
ended_at        14
energy_kwh       0
status           0
dtype: int64

In [51]:
telemetry.isna().sum()

station_id                0
observed_at               0
occupied_connectors     224
available_connectors      0
dtype: int64

In [52]:
maintenance.isna().sum()

maintenance_id      0
station_id          0
connector_no        0
started_at          0
ended_at            0
maintenance_type    0
cost_eur            9
dtype: int64

In [53]:
stations.isna().sum()

station_id                0
station_name              0
district                  0
site_type                 0
opened_on                 0
connector_count           0
connector_max_power_kw    0
dtype: int64

In [59]:
(sessions.isna().mean()*100).round(2)

session_id      0.0
station_id      0.0
connector_no    0.0
started_at      0.0
ended_at        0.6
energy_kwh      0.0
status          0.0
dtype: float64

**Exercice :** Traiter toutes les dates (de toutes les DataFrame)

- `maintenance.csv`
- `telemetry.csv`
- `stations.csv`

In [61]:
sessions["started_at"] = pd.to_datetime(sessions["started_at"])
sessions["ended_at"] = pd.to_datetime(sessions["ended_at"])

stations["opened_on"] = pd.to_datetime(stations["opened_on"])

telemetry["observed_at"] = pd.to_datetime(telemetry["observed_at"])

maintenance["ended_at"] = pd.to_datetime(maintenance["ended_at"])
maintenance["started_at"] = pd.to_datetime(maintenance["started_at"])